list(
  h5("Browse the Single cell atlas of Symbiotic polyps."),
  p("Scroll down to query :"),
  p("1 - The expression of a single gene (FeaturePlot)"),
  p("2 - The expression of a list of genes (Dotplot)"),
  p("3 - The full table of marker genes"),
  hr(),
  img(src = "img/Symbiotic_atlas_dimplot_screenshot.png",style="width: 300px"),
  hr(),
  h4("1 - Query the expression of a single gene (FeaturePlot)"),
  fluidRow(column(3,list(textInput("query_feature_symAtlas", "Enter a LOC gene ID", ""),
                         actionButton("plot_featureplot_symAtlas_button", "plot"))),
           column(7,list(plotOutput("FeaturePlot_SymAtlas"),
                         dataTableOutput("subset_fun_annot_feature"),
                         dataTableOutput("subset_marker_feature")))),
  # p("annotation for this gene (Fun annotation and expression)"),
  fluidRow(),
  hr(),
  h4("2 - Query the expression of a list of genes (DotPlot)"),
  fluidRow(column(3,list(textInput("query_list_of_gene_ids_sym_atlas", "Enter a list of \",\" separated IDs", ""),
                         actionButton("search_button_list_of_features_sym_atlas", "plot"))),
           column(7,list(plotOutput("DotPlot_SymAtlas"),
                         dataTableOutput("subset_fun_annot_feature_list"),
                         dataTableOutput("subset_marker_feature_list")))),
  hr(),
  h4("3 - Query the table of marker genes by keyword"),
  # uiOutput("column_selector"),
  dataTableOutput("table_markers_Sym_atlas")
)